[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "caddy file-server --listen :$PORT --root dist --try-files {path} /index.html"
